api_key: <Your API Key>
api_base: "https://api.openai.com/v1"
model: gpt-4o-mini
temperature: 0
toolbench_url: http://8.218.239.54:8080/rapidapi
tools_folder: "./server/tools"
cache_folder: "./server/tool_response_cache"
is_save: False
port: 8080

tool_info_path : "./stable_graph_metric/edge_files/after_coor_before_emb.json"
saved_path : "./stable_graph_metric/saved_results/"
